version: '3'
services:
    node_server:
        image: hugorgs/node_cli
        container_name: node_server
        stdin_open: true
        tty: true
        command: "/bin/bash"
        ports:
            - "4200:4200"
        volumes:
            - ${PROJECT_FOLDER}:/tmp
    orthanc:
        image: jodogne/orthanc-plugins
        ports:
            - "8042:8042"
        volumes: 
            - ${PROJECT_FOLDER}orthanc.json:/etc/orthanc/orthanc.json:ro
            - ${PROJECT_FOLDER}dist/boku-no-dicom-viewer/:/home/bndv/